#!/usr/bin/env bash
set -e

MAXPACK_HOME="${MAXPACK_HOME:-$HOME/.maxpack}"
MAXPACK_REPO="https://github.com/achengli/maxpack.git"
MAXPACK_SOURCE="$(cd "$(dirname "$0")" && pwd)"

echo "=== maxpack installer ==="
echo ""

mkdir -p "$MAXPACK_HOME/bin"

if [ -d "$MAXPACK_HOME/repo/.git" ]; then
  echo "=> Updating maxpack..."
  git -C "$MAXPACK_HOME/repo" pull --rebase || true
elif [ -d "$MAXPACK_HOME/repo" ]; then
  echo "=> Reinstalling maxpack from local source: $MAXPACK_SOURCE"
  rm -rf "$MAXPACK_HOME/repo"
  mkdir -p "$MAXPACK_HOME/repo"
  cp -r "$MAXPACK_SOURCE"/* "$MAXPACK_HOME/repo/"
else
  if [ -f "$MAXPACK_SOURCE/maxpack.asd" ]; then
    echo "=> Installing maxpack from local source: $MAXPACK_SOURCE"
    mkdir -p "$MAXPACK_HOME/repo"
    cp -r "$MAXPACK_SOURCE"/* "$MAXPACK_HOME/repo/"
  else
    echo "=> Cloning maxpack..."
    git clone "$MAXPACK_REPO" "$MAXPACK_HOME/repo"
  fi
fi

cat > "$MAXPACK_HOME/bin/maxpack" << 'MAXPACK_CLI_SCRIPT'
#!/usr/bin/env bash
MAXPACK_HOME="${MAXPACK_HOME:-$HOME/.maxpack}"
MAXPACK_CLI_ARGS=""
for MP_ARG in "$@"; do
  MAXPACK_CLI_ARGS="$MAXPACK_CLI_ARGS \"$MP_ARG\""
done
exec sbcl --noinform --non-interactive \
  --eval "(require 'asdf)" \
  --eval "(push \"$MAXPACK_HOME/repo/\" asdf:*central-registry*)" \
  --eval "(asdf:load-system :maxpack)" \
  --eval "(maxpack:Maxpack-Cli $MAXPACK_CLI_ARGS)" \
  --quit
MAXPACK_CLI_SCRIPT

chmod +x "$MAXPACK_HOME/bin/maxpack"

if [ ! -f "$MAXPACK_HOME/package.list" ]; then
  cat > "$MAXPACK_HOME/package.list" << 'LIST'
# maxpack package list
# Add packages to install, one per line:
#   user/repo             — GitHub shorthand (installs to pkg/latest/)
#   user/repo@tag         — with a specific tag (installs to pkg/tag/)
#   https://gitlab.com/user/repo.git  — full git URL
#
# Example:
#   achengli/maxpack
LIST
fi

echo ""
echo "maxpack installed successfully."
echo ""
echo "Add this to your shell config (~/.bashrc, ~/.zshrc, etc.):"
echo "  export PATH=\"\$HOME/.maxpack/bin:\$PATH\""
echo ""
echo "=> Configuring ~/.maxima/maxima-init.mac ..."
MAXIMA_INIT="$HOME/.maxima/maxima-init.mac"
mkdir -p "$(dirname "$MAXIMA_INIT")"
INIT_BLOCK="
/* === maxpack (auto-generated by install.sh) === */

import(pkg,[v]) :=
  if length(v) = 0
    then load(sconcat(\"$HOME/.maxpack/\", pkg, \"/latest/src/init.mac\"))
    else load(sconcat(\"$HOME/.maxpack/\", pkg, \"/\", v[1], \"/src/init.mac\"))\$
install([pkg]) :=
  if length(pkg) = 0
    then system(\"maxpack install\")
    else system(sconcat(\"maxpack install \", pkg[1]))\$
list()      := system(\"maxpack list\")\$
remove(pkg,[v]) :=
  if length(v) = 0
    then system(sconcat(\"maxpack remove \", pkg))
    else system(sconcat(\"maxpack remove \", pkg, \" \", v[1]))\$
update([pkg]) :=
  if length(pkg) = 0
    then system(\"maxpack update\")
    else system(sconcat(\"maxpack update \", pkg[1]))\$
exists(pkg,[v]) :=
  if length(v) = 0
    then system(sconcat(\"maxpack exists \", pkg))
    else system(sconcat(\"maxpack exists \", pkg, \" \", v[1]))\$
info(pkg,[v]) :=
  if length(v) = 0
    then system(sconcat(\"maxpack info \", pkg))
    else system(sconcat(\"maxpack info \", pkg, \" \", v[1]))\$
version()   := system(\"maxpack version\")\$
"
MARKER="=== maxpack (auto-generated by install.sh) ==="
if [ -f "$MAXIMA_INIT" ] && grep -qF "$MARKER" "$MAXIMA_INIT" 2>/dev/null; then
  echo "   (already configured)"
else
  echo "$INIT_BLOCK" >> "$MAXIMA_INIT"
  echo "   added to $MAXIMA_INIT"
fi
echo ""
echo "Package layout:"
echo "  ~/.maxpack/pkg-name/latest/   — default (updated via 'update')"
echo "  ~/.maxpack/pkg-name/v1.0/     — specific version"
echo ""
echo "Usage: maxpack install"
